"use client";
import dynamic from "next/dynamic";
import type { ComponentType } from "react";
export const examples: Record<string, ComponentType> = {
  accordion: dynamic(() => import("@/components/examples/accordion")),
  alert: dynamic(() => import("@/components/examples/alert")),
  "alert-dialog": dynamic(() => import("@/components/examples/alert-dialog")),
  "aspect-ratio": dynamic(() => import("@/components/examples/aspect-ratio")),
  attachment: dynamic(() => import("@/components/examples/attachment")),
  avatar: dynamic(() => import("@/components/examples/avatar")),
  badge: dynamic(() => import("@/components/examples/badge")),
  breadcrumb: dynamic(() => import("@/components/examples/breadcrumb")),
  bubble: dynamic(() => import("@/components/examples/bubble")),
  button: dynamic(() => import("@/components/examples/button")),
  "button-group": dynamic(() => import("@/components/examples/button-group")),
  calendar: dynamic(() => import("@/components/examples/calendar")),
  card: dynamic(() => import("@/components/examples/card")),
  carousel: dynamic(() => import("@/components/examples/carousel")),
  chart: dynamic(() => import("@/components/examples/chart")),
  checkbox: dynamic(() => import("@/components/examples/checkbox")),
  collapsible: dynamic(() => import("@/components/examples/collapsible")),
  combobox: dynamic(() => import("@/components/examples/combobox")),
  command: dynamic(() => import("@/components/examples/command")),
  "context-menu": dynamic(() => import("@/components/examples/context-menu")),
  "data-table": dynamic(() => import("@/components/examples/data-table")),
  "date-picker": dynamic(() => import("@/components/examples/date-picker")),
  dialog: dynamic(() => import("@/components/examples/dialog")),
  direction: dynamic(() => import("@/components/examples/direction")),
  drawer: dynamic(() => import("@/components/examples/drawer")),
  "dropdown-menu": dynamic(() => import("@/components/examples/dropdown-menu")),
  empty: dynamic(() => import("@/components/examples/empty")),
  field: dynamic(() => import("@/components/examples/field")),
  "hover-card": dynamic(() => import("@/components/examples/hover-card")),
  input: dynamic(() => import("@/components/examples/input")),
  "input-group": dynamic(() => import("@/components/examples/input-group")),
  "input-otp": dynamic(() => import("@/components/examples/input-otp")),
  item: dynamic(() => import("@/components/examples/item")),
  kbd: dynamic(() => import("@/components/examples/kbd")),
  label: dynamic(() => import("@/components/examples/label")),
  marker: dynamic(() => import("@/components/examples/marker")),
  menubar: dynamic(() => import("@/components/examples/menubar")),
  message: dynamic(() => import("@/components/examples/message")),
  "message-scroller": dynamic(
    () => import("@/components/examples/message-scroller"),
  ),
  "native-select": dynamic(() => import("@/components/examples/native-select")),
  "navigation-menu": dynamic(
    () => import("@/components/examples/navigation-menu"),
  ),
  pagination: dynamic(() => import("@/components/examples/pagination")),
  popover: dynamic(() => import("@/components/examples/popover")),
  progress: dynamic(() => import("@/components/examples/progress")),
  questionnaire: dynamic(() => import("@/components/examples/questionnaire")),
  "radio-group": dynamic(() => import("@/components/examples/radio-group")),
  resizable: dynamic(() => import("@/components/examples/resizable")),
  "scroll-area": dynamic(() => import("@/components/examples/scroll-area")),
  select: dynamic(() => import("@/components/examples/select")),
  separator: dynamic(() => import("@/components/examples/separator")),
  sheet: dynamic(() => import("@/components/examples/sheet")),
  sidebar: dynamic(() => import("@/components/examples/sidebar")),
  skeleton: dynamic(() => import("@/components/examples/skeleton")),
  slider: dynamic(() => import("@/components/examples/slider")),
  spinner: dynamic(() => import("@/components/examples/spinner")),
  switch: dynamic(() => import("@/components/examples/switch")),
  table: dynamic(() => import("@/components/examples/table")),
  tabs: dynamic(() => import("@/components/examples/tabs")),
  textarea: dynamic(() => import("@/components/examples/textarea")),
  toast: dynamic(() => import("@/components/examples/toast")),
  toggle: dynamic(() => import("@/components/examples/toggle")),
  "toggle-group": dynamic(() => import("@/components/examples/toggle-group")),
  tooltip: dynamic(() => import("@/components/examples/tooltip")),
  typography: dynamic(() => import("@/components/examples/typography")),
};
